# Generated by Django 4.1.4 on 2022-12-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_capital_id_alter_capital_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
